export const messageError = {
  EmailPassName: { err: ",nombre, email o password incorrecto" },
  Pass: { err: "password incorrecto" },
  EmailPass: { err: "email o password incorrecto" },
  EmailUsed: { err: "email ya usado" },
  Email: { err: "email incorrecto" },
  Later: { err: "error, intentelo mas tarde" },
  Token: { err: "token no valido" },
  DataBase: { err: "error base de datos, intentelo mas tarde" },
  NotFile: { err: "error no se encuentra el fichero" },
  Verification: {
    err: " debes verificar el email, se ha mandando un correo de verificación",
  },
  FileType: { err: " tipo de archivo no soportado" },
  NotFile: { err: "no existe archivo" },
  MaxSize: { err: "tamaño maximo exedido" },
  DescriptionTitleDifficulty: {
    err: "Descripcion , titulo o dificultad incorrecta",
  },
  fileData: { err: "datos del archivo incorrectos" },
  Calification: { err: "Esta ruta ya ha sido calificada" },
  CalificationFormat: { err: "LA calificacion debe ser un numero entre 0 y 4" },
  ruteNotExist: { err: "La ruta no existe" },
  description: { err: "Descricion incorrecta minimo 2 caracteres" },
};
